export type KnowledgeItem = {
  id: string;
  title: string;
  category: string;
  content: string;
  resource: string;
  keywords: string[];
};

export const knowledgeBase: KnowledgeItem[] = [
  {
    id: "student-visa",
    title: "Student visa and CAS guidance",
    category: "visa/immigration",
    content:
      "The official Student visa guidance on GOV.UK explains eligibility, Confirmation of Acceptance for Studies (CAS), applying or extending a visa, financial and English language requirements, dependants, and conditions such as work limits during study. Individual immigration circumstances, including a withdrawn or refused CAS, a visa close to expiry, a change of course or sponsor, a refusal, or questions about a student's immigration status must be referred to a qualified adviser or staff member. The assistant may provide the official guidance link but must not interpret immigration rules for an individual's situation.",
    resource: "https://www.gov.uk/student-visa",
    keywords: [
      "visa",
      "student visa",
      "immigration",
      "cas",
      "confirmation of acceptance for studies",
      "brp",
      "sponsor",
      "visa expiry",
      "visa expires",
      "visa extension",
      "right to stay",
      "immigration status",
    ],
  },
  {
    id: "hardship-fund",
    title: "University Hardship Fund",
    category: "financial",
    content:
      "The University Hardship Fund provides discretionary one-off grants for students facing unexpected or short-term financial difficulty. Examples include a delayed maintenance loan, bursary or scholarship payment, an unexpected essential cost, a sudden loss of income, or being temporarily unable to cover rent, food or utilities. Most enrolled students can apply, including international students. Applications are made online and normally require a short explanation and basic evidence such as bank statements or a letter about a delayed payment. Standard decisions usually take five to ten working days. A faster emergency route is available where a student is at immediate risk of being unable to afford essentials. If rent or other essentials are due within days, the student can be directed to the emergency route and serious situations may also need staff awareness.",
    resource: "/resources/hardship-fund",
    keywords: [
      "hardship",
      "hardship fund",
      "money",
      "financial",
      "financial difficulty",
      "rent",
      "food",
      "utilities",
      "grant",
      "scholarship",
      "scholarship instalment",
      "scholarship payment",
      "bursary",
      "maintenance loan",
      "delayed payment",
      "lost job",
      "loss of income",
      "income",
      "emergency money",
      "cannot afford",
      "can't afford",
    ],
  },
  {
    id: "deposit-guide",
    title: "Tenancy deposit guidance",
    category: "housing",
    content:
      "For an assured shorthold tenancy in England and Wales, a landlord or letting agent who takes a deposit must protect it in a government-approved tenancy deposit scheme and tell the tenant which scheme holds it within 30 days. At the end of the tenancy, the deposit should normally be returned unless there is a legitimate reason for deductions, such as unpaid rent, unpaid bills, or damage beyond fair wear and tear. If a student disagrees with proposed deductions, they can first ask for an itemised breakdown and evidence and try to resolve the issue in writing. Approved schemes provide a free independent dispute resolution service. Students should keep useful evidence such as their tenancy agreement, inventories, photographs and correspondence. This is general information rather than legal advice. Complex cases, including an unprotected deposit, large disputed sums or possible court action, should be referred to the students' union advice service or a specialist housing adviser.",
    resource: "/resources/deposit-guide",
    keywords: [
      "deposit",
      "tenancy deposit",
      "landlord",
      "letting agent",
      "housing",
      "renting",
      "rental",
      "deduction",
      "deductions",
      "deposit dispute",
      "deposit back",
      "return deposit",
      "tenancy",
      "wear and tear",
      "deposit scheme",
    ],
  },
  {
    id: "library",
    title: "Academic resources, past papers and reading lists",
    category: "academic",
    content:
      "Past exam papers, module reading lists and core study materials are available through the university library portal. Students sign in with their university account and can use their module pages to find current reading lists, lecture materials and available past-paper archives. Reading lists are organised by module code, so having the course or module details helps when searching. Not every module has a complete set of past papers. If something is missing, the student can contact their module leader or academic liaison librarian.",
    resource: "/resources/library",
    keywords: [
      "exam",
      "exam paper",
      "exam papers",
      "past exam",
      "past exams",
      "past paper",
      "past papers",
      "reading list",
      "reading lists",
      "library",
      "library portal",
      "module",
      "module code",
      "course materials",
      "study materials",
      "lecture materials",
    ],
  },
  {
    id: "extenuating-circumstances",
    title: "Extenuating circumstances and assessment mitigation",
    category: "academic",
    content:
      "Students whose ability to complete an assessment or meet a deadline has been affected by illness, bereavement, or another serious and unforeseen event can usually apply for extenuating or mitigating circumstances. Possible outcomes can include a short extension, deferring an assessment to a later sitting, or having the circumstances considered by an exam board. Applications are normally made online before or shortly after the affected assessment and usually require a short statement and supporting evidence such as a medical note. Deadlines and acceptable evidence vary by department, so time-critical or particularly distressing situations may also need staff attention. The process does not guarantee a particular outcome.",
    resource: "/resources/extenuating-circumstances",
    keywords: [
      "extenuating",
      "extenuating circumstances",
      "mitigating circumstances",
      "mitigation",
      "assessment",
      "deadline",
      "extension",
      "exam",
      "bereavement",
      "illness",
      "medical note",
      "deferral",
      "defer exam",
      "missed deadline",
    ],
  },
  {
    id: "it-help",
    title: "IT and account support",
    category: "other",
    content:
      "The university IT service desk supports problems with university accounts and systems, including sign-in issues, email, the virtual learning environment, Wi-Fi, software, password resets and multi-factor authentication. Common problems such as forgotten passwords, locked accounts or setting up multi-factor authentication on a new phone can usually be handled through the self-service portal or by contacting the IT service desk.",
    resource: "/resources/it-help",
    keywords: [
      "it",
      "it support",
      "login",
      "log in",
      "sign in",
      "password",
      "password reset",
      "locked out",
      "account",
      "email",
      "computer",
      "wifi",
      "wi-fi",
      "software",
      "system",
      "technical",
      "mfa",
      "multi-factor authentication",
      "vle",
    ],
  },
  {
    id: "disability-support",
    title: "Disability and additional learning support",
    category: "health/wellbeing",
    content:
      "Students with a disability, long-term health condition, mental-health condition or specific learning difficulty such as dyslexia can access tailored support. This may include reasonable adjustments for teaching and assessment, specialist mentoring, assistive technology, and help with Disabled Students' Allowance where eligible. Support usually begins by registering with the disability or inclusion service and completing a short needs assessment. This is normally routine support, but if the student describes being in crisis or unsafe, wellbeing and emergency procedures take priority.",
    resource: "/resources/disability-support",
    keywords: [
      "disability",
      "disabled",
      "long-term condition",
      "health condition",
      "learning difficulty",
      "dyslexia",
      "adjustment",
      "adjustments",
      "reasonable adjustments",
      "accessibility",
      "assistive technology",
      "disabled students allowance",
      "dsa",
      "inclusion service",
    ],
  },
  {
    id: "fees",
    title: "Fees, tuition and payment plans",
    category: "financial",
    content:
      "Questions about tuition fees, instalments and late payments are handled by the university finance or fees office. Payment plans may be available for students who are struggling to pay on time, and students should contact the fees office early to discuss available options. The assistant must not quote a student's balance, promise a particular payment arrangement or confirm an individual outcome because those depend on the student's university record.",
    resource: "/resources/fees",
    keywords: [
      "fee",
      "fees",
      "tuition",
      "tuition fee",
      "tuition fees",
      "payment",
      "payments",
      "payment plan",
      "instalment",
      "instalments",
      "late payment",
      "finance office",
      "fees office",
    ],
  },
  {
    id: "careers",
    title: "Careers and part-time work support",
    category: "other",
    content:
      "The university careers service can help students with CVs, applications, interviews, internships and finding part-time work alongside study. Support may be available through appointments, drop-ins and an online jobs board. For international students, working-hour limits and other right-to-work conditions depend on their visa. The assistant may provide careers support information and point students to official student visa guidance, but it must not advise an individual student about their immigration status or specific right to work.",
    resource: "/resources/careers",
    keywords: [
      "career",
      "careers",
      "job",
      "jobs",
      "part-time job",
      "part time job",
      "employment",
      "cv",
      "resume",
      "application",
      "applications",
      "interview",
      "internship",
      "internships",
      "work",
      "jobs board",
    ],
  },
  {
    id: "wellbeing",
    title: "Wellbeing and Counselling service",
    category: "health/wellbeing",
    content:
      "The Wellbeing and Counselling service supports students with non-urgent mental-health and wellbeing concerns such as stress, low mood, anxiety, homesickness, difficulty adjusting, sleep problems or academic pressure. Support can include short-term one-to-one counselling, group sessions, workshops and self-help resources, normally accessed through self-referral and an initial assessment. It is also appropriate where wellbeing difficulties are connected to another problem such as money or housing. This service is not an emergency service. A student who appears to be in crisis, feels unsafe, has thoughts of self-harm, or cannot keep themselves safe must be escalated to a person and directed to urgent support. If there is possible immediate danger, emergency support must be shown immediately.",
    resource: "/resources/wellbeing",
    keywords: [
      "wellbeing",
      "mental health",
      "mental-health",
      "stress",
      "stressed",
      "anxiety",
      "anxious",
      "low mood",
      "homesick",
      "homesickness",
      "sleep",
      "sleep problems",
      "overwhelmed",
      "counselling",
      "counseling",
      "cope",
      "coping",
      "struggling",
      "support",
    ],
  },
  {
    id: "report-and-support",
    title: "Report and Support",
    category: "health/wellbeing",
    content:
      "Students who have experienced harassment, bullying, hate or sexual misconduct can use the university's Report and Support service. The service normally offers options including anonymous reporting and speaking with a trained adviser. Because these disclosures are sensitive and may indicate risk, the assistant should respond carefully, provide the Report and Support route and escalate the case to a person rather than handling it entirely automatically. If there is any sign of immediate danger, emergency procedures apply.",
    resource: "/resources/report-and-support",
    keywords: [
      "harassment",
      "harassed",
      "bullying",
      "bullied",
      "hate",
      "hate incident",
      "sexual misconduct",
      "sexual harassment",
      "abuse",
      "assault",
      "report",
      "report and support",
    ],
  },
  {
    id: "samaritans",
    title: "Samaritans urgent mental-health support",
    category: "health/wellbeing",
    content:
      "Samaritans provides free and confidential emotional support by phone on 116 123 at any time of day or night. It is appropriate to share this number with someone who is struggling to cope or in distress. Sharing the number does not replace human escalation: any case showing crisis or risk must still reach a staff member.",
    resource: "tel:116123",
    keywords: [
      "samaritans",
      "crisis",
      "suicide",
      "suicidal",
      "self harm",
      "self-harm",
      "harm myself",
      "hurt myself",
      "unsafe",
      "distress",
      "cannot cope",
      "can't cope",
    ],
  },
  {
    id: "emergency",
    title: "Emergency services",
    category: "health/wellbeing",
    content:
      "999 is the UK emergency number for situations involving immediate danger to life or safety, including a medical emergency or an immediate threat to someone's safety. Where a student's message suggests possible immediate danger, the assistant should provide 999 straight away and the case must be treated as the highest priority and escalated immediately to a human.",
    resource: "tel:999",
    keywords: [
      "999",
      "emergency",
      "immediate danger",
      "danger",
      "danger right now",
      "unsafe",
      "not safe",
      "medical emergency",
      "life threatening",
      "life-threatening",
      "threat to safety",
    ],
  },
];
